name: shader_fxs
description: Flutter transitions using shaders.
version: 0.0.1
homepage: https://github.com/alnitak/flutter_shader_fxs

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

 assets:
   - assets/
